## Barrios Populares EDA
*El dataset de barrios populares contiene datos de relevamiento de los barrios populares en las distintas provincias argentinas. Estos datos son extraidos de la fuente oficial de https://datos.gob.ar/dataset/desarrollo-social-registro-nacional-barrios-populares.*

*Este dataset contiene 19 variables:*
- id_renabap = identificador oficial dado para cada barrio
- geometry = coordenadas de geolocalizacion de cada barrio, en formato (longitud, latitud)
- renabap_id = identificador oficial dado para cada barrio
- nombre_barrio = nombre de cada barrio
- provincia = provincia en la cual se ubica cada barrio
- departamento = departamento o municipio al cual pertenece cada barrio
- localidad = ciudad donde se ubica el barrio
- cantidad_viviendas_aproximadas 
- cantidad_familias_aproximada 
- decada_de_creacion
- anio_de_creacion 
- energia_electrica = tipo de conexion para abastecer de energia electrica a las viviendas
- efluentes_cloacales = tipo de desague cloacal que posee cada barrio
- agua_corriente = tipo de conexion para abastecer de agua al barrio
- cocina = tipo de conexion para un artefacto cocina
- calefaccion = tipo de calefaccion que posee cada barrio
- situacion_dominial
- clasificacion_barrio = contiene 3 valores posibles, puede ser una Villa, un Asentamiento o un Conjunto habitacional degradado
- superficie_m2 = area total ocupada por el barrio

In [36]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import ssl
import matplotlib.pyplot as plt

ssl._create_default_https_context = ssl._create_unverified_context

In [37]:
url = "https://datos.gob.ar/dataset/desarrollo-social-registro-nacional-barrios-populares"

In [38]:
csv_links = None
df_barrios_populares = None
df_ref_barrios_populares = None

res = requests.get(url)
if res.status_code == 200:
    soup = BeautifulSoup(res.text, 'lxml')
    all_links = soup.find_all('a')
    csv_links = [link['href'] for link in all_links if 'csv' in link['href']]

if len(csv_links) > 0:
    print(csv_links[0])
    df_barrios_populares = pd.read_csv(csv_links[0])
    df_ref_barrios_populares = pd.read_csv(csv_links[1])
else:
    df_barrios_populares = pd.read_csv('./CSV/2023-09-20_info_publica.csv')
    df_ref_barrios_populares = pd.read_csv('./CSV/referencia_datos.csv')

https://datosabiertos.desarrollosocial.gob.ar/dataset/0d022767-9390-486a-bff4-ba53b85d730e/resource/9a951270-60dd-4f21-aa19-4ef1205620bd/download/2023-09-20_info_publica.csv

In [39]:
df_ref_barrios_populares

,variable,valores_posibles,descripcion_valores
0,energia_electrica,Conexión formal a la red con medidor domicilia...,Modo óptimo y seguro de conexión. Servicio ope...
1,energia_electrica,Conexión regular a la red con medidor domicili...,No se paga por el servicio y quien lo recibe n...
2,energia_electrica,Conexión regular a la red con medidor domicili...,Conexión de menor potencia que dificulta o imp...
3,energia_electrica,Conexión regular a la red con medidor prepago,"Las familias deben ir a un kiosco, local de pa..."
4,energia_electrica,Conexión a la red con medidor compartido,Dos o más domicilios comparten un único medido...
5,energia_electrica,Conexión a la red con medidor comunitario,"Generalmente se encuentra en altura, mide el c..."
6,energia_electrica,Conexión irregular a la red,"Enganchados a la red, cables a los postes de l..."
7,energia_electrica,No tiene conexión eléctrica,No acceden a la red ni a ningún modo alternativo.
8,energia_electrica,Energía solar,Modo alternativo.
9,energia_electrica,Generador eléctrico a combustión,Modo alternativo.
10,efluentes_cloacales,Conexión formal a la red cloacal,Modo óptimo y seguro de conexión. Servicio ope...
11,efluentes_cloacales,Red cloacal conectada a la red pluvial,Conexión formal pero conectada con el alcantar...
12,efluentes_cloacales,Conexión irregular a la red cloacal,Enganchados informalmente a las cañerías colec...
13,efluentes_cloacales,Desagüe a cámara séptica y pozo ciego,La cámara séptica es una estructura que permit...
14,efluentes_cloacales,Desagüe sólo a pozo negro/ciego u hoyo,Excavación en el terreno que recibe la descarg...
15,efluentes_cloacales,Baño seco,Tipo de baño ecológico que se caracteriza por ...
16,efluentes_cloacales,Desagüe a intemperie o cuerpo de agua,"Drena directo a la calle, zanja, arroyo, etc."
17,agua_corriente,Conexión formal a la red de agua con factura,Modo óptimo y seguro de la conexión a la red d...
18,agua_corriente,Conexión regular a la red de agua pero sin fac...,No se paga por el servicio de agua corriente y...
19,agua_corriente,Conexión regular a la red de agua con tarifa c...,Dos o más domicilios comparten una única conex...
20,agua_corriente,Conexión irregular a la red de agua,Enganchados informalmente a la red de agua cor...
21,agua_corriente,Bomba de agua de pozo domiciliaria,"Se extrae el agua de las napas freáticas, cont..."
22,agua_corriente,Bomba de agua de pozo comunitaria,"Se extrae el agua de las napas freáticas, habi..."
23,agua_corriente,Canilla comunitaria dentro del barrio,Se accede al agua mediante canillas de libre a...
24,agua_corriente,Camión cisterna,Regularmente un camión trae agua al barrio par...
25,agua_corriente,Acarreo de baldes desde fuera del barrio,No hay ninguna fuente de agua corriente en el ...
26,agua_corriente,"Vertiente, arroyo, río o canal",Se consume agua proveniente de una fuente natu...
27,agua_corriente,Cosecha/Recolección de agua de lluvia,Se consume agua proveniente de la recolección ...
28,cocina,Conexión formal a la red de gas,Modo óptimo y seguro de la conexión a la red d...
29,cocina,Conexión irregular a la red de gas,Enganchados informalmente a la red de gas natu...
30,cocina,Gas en garrafa,Gas envasado que las familias se autoproveen.
31,cocina,Leña o carbón,Se genera calor a través de la quema de estos ...
32,cocina,Energía eléctrica,microondas/calentador/horno eléctrico.
33,calefaccion,Conexión formal a la red de gas,Modo óptimo y seguro de la conexión a la red d...
34,situacion_dominial,Título de propiedad,La mayoría de los vecinos cuentan con título d...
35,situacion_dominial,Propiedad Comunitaria,NaN
36,situacion_dominial,Otro tipo de seguridad en la tenencia,La mayoría de los vecinos cuentan con otro tip...
37,situacion_dominial,Boleto de compra-venta,La mayoría de los vecinos cuentan con boleto d...
38,situacion_dominial,Ninguna seguridad en la tenencia,La mayoría de los vecinos no tiene título de p...
39,calefaccion,Conexión irregular a la red de gas,Enganchados informalmente a la red de gas natu...
40,clasificacion_barrio,Asentamiento,NaN
41,clasificacion_barrio,Villa,NaN
42,clasificacion_barrio,Conjunto habitacional degradado,NaN
43,calefaccion,Gas en garrafa,Gas envasado que las familias se autoproveen.
44,calefaccion,Leña o carbón,Se genera calor a través de la quema de estos ...
45,calefaccion,Energía eléctrica,estufa eléctrica/resistencia.
46,calefaccion,Inexistente,No acceden a la red ni a ningún modo alternati...
47,calefaccion,Otro / vacío,Celda vacía a la que le pusimos esta denominac...

In [40]:
df_barrios_populares.head()

,id_renabap,geometry,renabap_id,nombre_barrio,provincia,departamento,localidad,cantidad_viviendas_aproximadas,cantidad_familias_aproximada,decada_de_creacion,anio_de_creacion,energia_electrica,efluentes_cloacales,agua_corriente,cocina,calefaccion,situacion_dominial,clasificacion_barrio,superficie_m2
0,1,MULTIPOLYGON (((-58.83350090114561 -34.4812767...,1,Monterrey I,Buenos Aires,Pilar,Presidente Derqui,40,44,Década 1990,NaN,Conexión regular a la red con medidor prepago,Desagüe a cámara séptica y pozo ciego,Bomba de agua de pozo domiciliaria,Gas en garrafa,Sin Datos,NO,Asentamiento,11674
1,2,MULTIPOLYGON (((-58.012000483529214 -34.947319...,2,Malvinas II,Buenos Aires,La Plata,José Melchor Romero,290,319,Década 1990,NaN,Conexión irregular a la red,Desagüe a cámara séptica y pozo ciego,Conexión irregular a la red de agua,Gas en garrafa,Leña o carbón,NO,Asentamiento,98034
2,3,MULTIPOLYGON (((-58.07980353023293 -35.0350737...,3,Ferroviario,Buenos Aires,La Plata,Angel Etcheverry,133,146,Década 2000,NaN,Conexión irregular a la red,Desagüe sólo a pozo negro/ciego u hoyo,Conexión formal a la red de agua con factura,Gas en garrafa,Leña o carbón,NO,Asentamiento,75850
3,4,MULTIPOLYGON (((-57.97991397438435 -34.9083356...,4,La Favelita,Buenos Aires,La Plata,Tolosa,122,134,Década 1970,NaN,Conexión irregular a la red,Desagüe sólo a pozo negro/ciego u hoyo,Conexión irregular a la red de agua,Gas en garrafa,Energía eléctrica,NO,Asentamiento,36865
4,5,MULTIPOLYGON (((-58.062970366820394 -34.901341...,5,Casaca,Buenos Aires,La Plata,City Bell,20,22,Década 2000,NaN,Conexión irregular a la red,Desagüe a cámara séptica y pozo ciego,Bomba de agua de pozo domiciliaria,Gas en garrafa,Sin Datos,NO,Asentamiento,25754

In [41]:
df_barrios_populares.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5687 entries, 0 to 5686
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id_renabap                      5687 non-null   int64
 1   geometry                        5687 non-null   object
 2   renabap_id                      5687 non-null   int64
 3   nombre_barrio                   5687 non-null   object
 4   provincia                       5687 non-null   object
 5   departamento                    5687 non-null   object
 6   localidad                       5687 non-null   object
 7   cantidad_viviendas_aproximadas  5687 non-null   int64
 8   cantidad_familias_aproximada    5687 non-null   int64
 9   decada_de_creacion              5687 non-null   object
 10  anio_de_creacion                1292 non-null   float64
 11  energia_electrica               5687 non-null   object
 12  efluentes_cloacales             5687 non-null   object
 13  agua_corriente                  5687 non-null   object
 14  cocina                          5687 non-null   object
 15  calefaccion                     5687 non-null   object
 16  situacion_dominial              5687 non-null   object
 17  clasificacion_barrio            5687 non-null   object
 18  superficie_m2                   5687 non-null   int64
dtypes: float64(1), int64(5), object(13)
memory usage: 844.3+ KB

In [42]:
df_barrios_populares.columns

Index(['id_renabap', 'geometry', 'renabap_id', 'nombre_barrio', 'provincia',
       'departamento', 'localidad', 'cantidad_viviendas_aproximadas',
       'cantidad_familias_aproximada', 'decada_de_creacion',
       'anio_de_creacion', 'energia_electrica', 'efluentes_cloacales',
       'agua_corriente', 'cocina', 'calefaccion', 'situacion_dominial',
       'clasificacion_barrio', 'superficie_m2'],
      dtype='object')